### ISSUE TITLE
Section Width isn't responsive

### ISSUE THREAD

**Issue by kijanawoodard** [Kimeiga/bahunya#10]
Thank you for this project!
Dropped it in. Works well.

I was caught off guard by the width of html5 sections. For me they rendered at 900px, regardless of the width of the viewport.

https://github.com/Kimeiga/bahunya/blob/master/scss/_grid.scss#L44

I added an override after pulling from the cdn.
 section {
                width: auto; /* set to 900px in source */
}

**Comment by Kimeiga** [comment]
Hi Kijana! 

It's been forever but I finally got around to reworking the whole framework.

I agree that setting the width of sections for no reason was not a great idea; so now they are only given a humble margin:

```css
section {
  margin: 20px 0;
}
```

You'll have to drop in the new CDN link as I have changed the folder structure quite a lot.

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kimeiga/bahunya/dist/bahunya.min.css">
```

Cheers and thanks for making an issue!
