### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by jcbhmr** [Kimeiga/bahunya#13]
![image](https://user-images.githubusercontent.com/61068799/216210198-751b0477-b9b2-46a7-9952-d662776b96f5.png)

**Comment by tfukaza** [comment]
Yes

**Comment by jcbhmr** [comment]
/re @tfukaza Awesome! ❤

Is there going to be progress on https://github.com/Kimeiga/bahunya/pull/12 and maybe https://github.com/Kimeiga/bahunya/issues/11 ? If I open a PR, will it sit for 6 months?

**Comment by Kimeiga** [comment]
Haha yeah it's been a bit. Is there anything you want added

**Comment by jcbhmr** [comment]
I'd love to see a light version! That's my top request. It seems like there's been some discussion in #11 that it could happen.
