### ISSUE TITLE
Code inside pre is broken

### ISSUE THREAD

**Issue by akhyarrh** [Kimeiga/bahunya#7]
See image:
![Screenshot 2020-10-25 143747](https://user-images.githubusercontent.com/10618799/97114945-81e2f000-172e-11eb-8beb-f21807e17a95.png)

Possible fix by adding: `pre code { background: none }`

**Comment by Kimeiga** [comment]
Hi Akhyar! 

It's been forever but I finally got around to reworking the whole framework.

I agree that the previous pre>code functionality looked pretty jank. I believe all of this should be fixed now with the new framework. 

You'll have to drop in the new CDN link as I have changed the folder structure quite a lot.

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kimeiga/bahunya/dist/bahunya.min.css">
```

Cheers and thanks for making an issue!
