### ISSUE TITLE
Project maintenance status

### ISSUE THREAD

**Issue by Bert-Proesmans** [Kimeiga/bahunya#9]
Hi,

I've been keeping my eye on this repo for a few months now.
There are various mentions about a code restructure or a kind of V2. Do you want to share more info about its progression?

I'm a fan of your principles, cheers!

**Comment by Kimeiga** [comment]
Thank you so much for your kind words; I am thinking of restarting from scratch soon and fixing all of the problems in the earlier issues but im royally dying by midterms at the moment; I cannot give you an eta for when i get off my ass and fix all of this but hopefully i'll have more time spring quarter!

**Comment by Kimeiga** [comment]
in the meantime check out "water.css" i think its the best classless css framework out there right now

**Comment by Bert-Proesmans** [comment]
Thank for the pointer!
And don't worry; i'm not sure either when I'm finally starting on the second iteration of my personal website ;)

Good luck with exams!

**Comment by Kimeiga** [comment]
Hi Proesmans! 

It's been forever but I finally got around to reworking the whole framework.

You'll have to drop in the new CDN link as I have changed the folder structure quite a lot.

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kimeiga/bahunya/dist/bahunya.min.css">
```

Cheers and thanks for making an issue!
